Nfq_nom_nom_homepage:
    pattern:  /
    defaults: { _controller: NfqNomNomBundle:Default:index }

Nfq_nom_nom_notifications:
    pattern:  /notifications
    defaults: { _controller: NfqNomNomBundle:Default:notifications }

Nfq_nom_nom_avatar_display:
    pattern:  /a/{avatarId}
    defaults: { _controller: NfqNomNomBundle:Account:getAvatar }

Nfq_nom_nom_event_manager:
    pattern:  /eventmanager/
    defaults: { _controller: NfqNomNomBundle:Event:eventManager }

Nfq_nom_nom_events:
    pattern: /event/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:event , eventId: 0}

Nfq_nom_nom_add_user_to_event:
    pattern: /event/addusers/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:addUsersToEvent , eventId: 0}

Nfq_nom_nom_add_recipe_to_event:
    pattern: /event/addrecipe/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:addRecipeToEvent , eventId: 0}

Nfq_nom_nom_create_event:
    pattern:  /createevent/
    defaults: { _controller: NfqNomNomBundle:Event:createEvent }

Nfq_nom_nom_accept_event:
    pattern:  /acceptevent/{userEventId}
    defaults: { _controller: NfqNomNomBundle:Event:acceptEvent }

Nfq_nom_nom_progress_event:
    pattern:  /progressevent/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:progressEvent }

Nfq_nom_nom_regress_event:
    pattern:  /regressevent/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:regressEvent }

Nfq_nom_nom_ready_to_progress:
    pattern:    /readytoprogres/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:readyToProgress }

Nfq_nom_nom_profile:
    pattern: /profile
    defaults: {_controller: NfqNomNomBundle:Account:profile }

Nfq_nom_nom_profile_edit:
    pattern: /profile/edit
    defaults: {_controller: NfqNomNomBundle:Account:profileEdit }

Nfq_nom_nom_password_change:
    pattern: /profile/change_password
    defaults: {_controller: NfqNomNomBundle:Account:changepassword }

nfq_nom_nom_recipe_list:
    pattern:  /recipes/{page}
    defaults: { _controller: NfqNomNomBundle:RecipesList:recipeList, page: 1}

nfq_nom_nom_recipe:
    pattern:  /recipe/{id}
    defaults: { _controller: NfqNomNomBundle:Recipes:recipe}

Nfq_nom_nom_create_recipe:
    pattern:  /createrecipe
    defaults: { _controller: NfqNomNomBundle:Recipes:createRecipe}

nfq_security_login:
    pattern: /login
    defaults: {_controller: NfqNomNomBundle:Account:login}

nfq_registration_register:
    pattern: /register
    defaults: {_controller: NfqNomNomBundle:Account:register}

nfq_registration_confirmed:
    pattern: /register/confirmed
    defaults: {_controller: NfqNomNomBundle:Account:confirmed}

Nfq_nom_nom_upvote_recipe:
    pattern:  /upvoterecipe/{userEventId}/{eventRecipeId}
    defaults: { _controller: NfqNomNomBundle:Recipes:upvoteRecipe}

Nfq_nom_nom_downvote_recipe:
    pattern:  /downvoterecipe/{userEventId}/{eventRecipeId}
    defaults: { _controller: NfqNomNomBundle:Recipes:downvoteRecipe}

Nfq_nom_nom_add_userproduct:
    pattern:  /adduserproduct/{userEventId}/{recipeProductId}
    defaults: { _controller: NfqNomNomBundle:Product:addUserProduct}

Nfq_forgot_password:
    pattern: /forgot_password
    defaults: {_controller: NfqNomNomBundle:Account:forgot}

Nfq_reset_password:
    pattern: /reset_password
    defaults: {_controller: NfqNomNomBundle:Account:reset}

Nfq_resetting_send_email:
    pattern: /reseting_send_email
    defaults: {_controller: NfqNomNomBundle:Account:sendEmail}

Nfq_resetting_check_email:
    pattern: /resetting_check_email
    defaults: {_controller: NfqNomNomBundle:Account:checkEmail}

Nfq_registration_register:
    pattern: /registration_register
    defaults: {_controller: NfqNomNomBundle:Account:checkREmail}

Nfq_nom_nom_create_product:
    pattern:  /createproduct
    defaults: { _controller: NfqNomNomBundle:Recipes:createProduct}

Nfq_test:
    pattern: /test
    defaults: {_controller: NfqNomNomBundle:Test:test}

