Nfq_nom_nom_homepage:
    pattern:  /
    defaults: { _controller: NfqNomNomBundle:Default:index }

Nfq_nom_nom_avatar_display:
    pattern:  /a/{avatarId}
    defaults: { _controller: NfqNomNomBundle:Default:getAvatar }

Nfq_nom_nom_event_manager:
    pattern:  /eventmanager/
    defaults: { _controller: NfqNomNomBundle:Event:eventManager }

Nfq_nom_nom_events:
    pattern: /event/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:event , eventId: 0}

Nfq_nom_nom_add_user_to_event:
    pattern: /event/addusers/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:addUsersToEvent , eventId: 0}

Nfq_nom_nom_create_event:
    pattern:  /createevent/
    defaults: { _controller: NfqNomNomBundle:Event:createEvent }

Nfq_nom_nom_profile:
    pattern: /profile
    defaults: {_controller: NfqNomNomBundle:Default:profile }

Nfq_nom_nom_profile_edit:
    pattern: /profile/edit
    defaults: {_controller: NfqNomNomBundle:Default:profileEdit }

Nfq_nom_nom_password_change:
    pattern: /profile/change_password
    defaults: {_controller: NfqNomNomBundle:Default:changepassword }

Nfq_nom_nom_recipe:
    pattern:  /recipe/{id}
    defaults: { _controller: NfqNomNomBundle:Recipes:recipe}

