Nfq_nom_nom_homepage:
    pattern:  /
    defaults: { _controller: NfqNomNomBundle:Default:index }

Nfq_nom_nom_avatar_display:
    pattern:  /a/{avatarId}
    defaults: { _controller: NfqNomNomBundle:Default:getAvatar }

Nfq_nom_nom_event_manager:
    pattern:  /eventmanager/
    defaults: { _controller: NfqNomNomBundle:Default:eventManager }

Nfq_nom_nom_events:
    pattern: /event/{eventId}
    defaults: { _controller: NfqNomNomBundle:Default:event , eventId: 0}

Nfq_nom_nom_create_event:
    pattern:  /createevent/
    defaults: { _controller: NfqNomNomBundle:Default:createEvent }