Nfq_nom_nom_homepage:
    pattern:  /
    defaults: { _controller: NfqNomNomBundle:Default:index }

Nfq_nom_nom_avatar_display:
    pattern:  /a/{avatarId}
    defaults: { _controller: NfqNomNomBundle:Account:getAvatar }

Nfq_nom_nom_event_manager:
    pattern:  /eventmanager/
    defaults: { _controller: NfqNomNomBundle:Event:eventManager }

Nfq_nom_nom_events:
    pattern: /event/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:event , eventId: 0}

Nfq_nom_nom_add_user_to_event:
    pattern: /event/addusers/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:addUsersToEvent , eventId: 0}

Nfq_nom_nom_add_recipe_to_event:
    pattern: /event/addrecipe/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:addRecipeToEvent , eventId: 0}

Nfq_nom_nom_create_event:
    pattern:  /createevent/
    defaults: { _controller: NfqNomNomBundle:Event:createEvent }

Nfq_nom_nom_accept_event:
    pattern:  /acceptevent/{userEventId}
    defaults: { _controller: NfqNomNomBundle:Event:acceptEvent }

Nfq_nom_nom_progress_event:
    pattern:  /progressevent/{eventId}
    defaults: { _controller: NfqNomNomBundle:Event:progressEvent }

Nfq_nom_nom_profile:
    pattern: /profile
    defaults: {_controller: NfqNomNomBundle:Account:profile }

Nfq_nom_nom_profile_edit:
    pattern: /profile/edit
    defaults: {_controller: NfqNomNomBundle:Account:profileEdit }

Nfq_nom_nom_password_change:
    pattern: /profile/change_password
    defaults: {_controller: NfqNomNomBundle:Account:changepassword }

nfq_nom_nom_recipe_list:
    pattern:  /recipe/
    defaults: { _controller: NfqNomNomBundle:RecipesList:recipeList}

nfq_nom_nom_recipe:
    pattern:  /recipe/{id}
    defaults: { _controller: NfqNomNomBundle:Recipes:recipe}

