parameters:
#    Nfq_nom_nom.example.class: Nfq\NomNomBundle\Example

services:
#    Nfq_nom_nom.example:
#        class: %Nfq_nom_nom.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
