parameters:
#    Nfq_nom_nom.example.class: Nfq\NomNomBundle\Example

services:
#    Nfq_nom_nom.example:
#        class: %Nfq_nom_nom.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     nfq_nom_nom.form.type.event:
        class: Nfq\NomNomBundle\Form\Type\EventType
        tags:
            - { name: form.type, alias: event }

     nfq_nom_nom.form.type.adduserstoevent:
         class: Nfq\NomNomBundle\Form\Type\AddUsersToEventType
         tags:
             - { name: form.type }

     nfq_nom_nom.form.type.addrecipetoevent:
          class: Nfq\NomNomBundle\Form\Type\AddRecipeToEventType
          tags:
              - { name: form.type, alias: addrecipetoevent }

     nfq_nom_nom.form.type.userproducttype:
          class: Nfq\NomNomBundle\Form\Type\UserProductType
          tags:
              - { name: form.type, alias: userproducttype }