parameters:
#    Nfq_nom_nom.example.class: Nfq\NomNomBundle\Example

services:
#    Nfq_nom_nom.example:
#        class: %Nfq_nom_nom.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     nfq_nom_nom.form.type.event:
        class: Nfq\NomNomBundle\Form\Type\EventType
        tags:
            - { name: form.type, alias: event }

     nfq_nom_nom.form.type.adduserstoevent:
         class: Nfq\NomNomBundle\Form\Type\AddUsersToEventType
         tags:
             - { name: form.type }

     nfq_nom_nom.form.type.addrecipetoevent:
          class: Nfq\NomNomBundle\Form\Type\AddRecipeToEventType
          tags:
              - { name: form.type, alias: addrecipetoevent }

     nfq_nom_nom.form.type.userproducttype:
          class: Nfq\NomNomBundle\Form\Type\UserProductType
          tags:
              - { name: form.type, alias: userproducttype }

     nfq_nom_nom.form.type.createrecipetype:
               class: Nfq\NomNomBundle\Form\Type\CreateRecipeType
               tags:
                   - { name: form.type, alias: createrecipetype }

     nfq_nom_nom.form.type.recipeproducttype:
               class: Nfq\NomNomBundle\Form\Type\RecipeProductType
               tags:
                   - { name: form.type, alias: recipeproducttype }

     nfq_nom_nom.twig.nfq_extension:
         class: Nfq\NomNomBundle\Twig\NfqExtension
         tags:
             - { name: twig.extension }
         arguments:
             doctrine: "@doctrine"

     nfq_nom_nom.form.type.browserecipes:
                    class: Nfq\NomNomBundle\Form\Type\BrowseRecipesType
                    tags:
                        - { name: form.type, alias: browserecipes }

     nfq_nom_nom.form.type.addtobrowserecipes:
                    class: Nfq\NomNomBundle\Form\Type\AddToBrowseRecipesType
                    tags:
                        - { name: form.type, alias: addtobrowserecipes }

     nfq_nom_nom.form.type.displaysearch:
                         class: Nfq\NomNomBundle\Form\Type\DisplaySearchType
                         tags:
                             - { name: form.type, alias: displaysearch }

     nfq_nom_nom.form.type.displayrecipe:
                              class: Nfq\NomNomBundle\Form\Type\DisplayRecipeType
                              tags:
                                  - { name: form.type, alias: displayrecipe }

     nfq_nom_nom.form.type.createproduct:
                                   class: Nfq\NomNomBundle\Form\Type\CreateProductType
                                   tags:
                                       - { name: form.type, alias: createproduct }