parameters:
#    vaiva_vaiva.example.class: Vaiva\VaivaBundle\Example

services:
#    vaiva_vaiva.example:
#        class: %vaiva_vaiva.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
