<?php

namespace Nfq\NomNomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MyNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyNotificationRepository extends EntityRepository
{
    public function findByEvent($eventId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT m FROM NfqNomNomBundle:MyNotification AS m JOIN m.myUserEvent AS ue
            WHERE ue.myEvent = :myevent')
            ->setParameters(array('myevent' => $eventId))
            ->getResult();
    }
}
