<?php

namespace Nfq\NomNomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MyProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyProductRepository extends EntityRepository
{
    public function checkExistence($name){
        return $this->getEntityManager()->createQuery(
            'SELECT p
             FROM NfqNomNomBundle:MyProduct AS p
             WHERE p.productName = :name
            '
        )->setParameter('name', $name)
         ->getResult();
    }
}
