<?php

namespace Nfq\NomNomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MyRecipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyRecipeRepository extends EntityRepository
{

    /**
     * Returns total recipes count
     *
     * @return \Doctrine\ORM\Query
     */
    public function getRecipesCount()
    {
        $q = $this->createQueryBuilder('r')
            ->select('count(r.id)');

        return $q->getQuery()->getSingleScalarResult();
    }

    /**
     * Returns recipes query
     *
     * @return \Doctrine\ORM\Query
     */
    public function getRecipesQuery()
    {
        $q = $this->createQueryBuilder('r')
            ->select('r');

        return $q->getQuery();
    }
}
