<?php

namespace Nfq\NomNomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MyUserEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyUserEventRepository extends EntityRepository
{
    public function findAllUserEventsByUserId($userId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT * FROM NfqNomNomBundle:MyUserEvent WHERE user_id = :Id'
            )
            ->setParameter('id',$userId)
            ->getResult();
    }
}
