<?php

namespace Nfq\NomNomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MyUserEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyUserEventRepository extends EntityRepository
{
    public function findUserEvent($event, $user)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM NfqNomNomBundle:MyUserEvent m WHERE m.myEvent = :event AND m.myUser = :useris'
            )
            ->setParameters(array('event' => $event,
                                'useris' =>$user))
            ->getResult();
    }

    public function findUsersInUserEvent($event)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT u.username FROM NfqNomNomBundle:MyUserEvent AS m JOIN m.myUser AS u WHERE m.myEvent = :event'
            )
            ->setParameters(array('event' => $event))
            ->getResult();
    }
}
